cloud:
  aws:
    credentials:
      accessKey: #AWS ACCESS KEY
      secretKey: #AWS SECRET KEY
    region:
      static: eu-central-1

destinationFolder: /tmp/sentinel/

spring:
  profiles:
    active: http

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
