cloud:
  aws:
    credentials:
      accessKey: #AWS ACCESS KEY
      secretKey: #AWS SECRET KEY
    region:
      static: eu-central-1

destinationFolder: /tmp/sentinel/

spring:
  profiles:
    active: http
